name: Node.js deployment

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm build

      - name: Install cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Deploy
        env:
          CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          cat <<EOF > ~/.ssh/config
          Host vps
          HostName ${{ secrets.SSH_HOST }}
          User ${{ secrets.SSH_USER }}
          IdentityFile ~/.ssh/id_ed25519
          ProxyCommand cloudflared access ssh --id ${{ secrets.CF_CLIENT_ID }} --secret ${{ secrets.CF_CLIENT_SECRET }} --hostname %h
          StrictHostKeyChecking no
          EOF

          ssh vps "mkdir -p /var/www/${{ github.event.repository.name }}/dist/ /var/www/${{ github.event.repository.name }}/public/dist"

          rsync -avz -e ssh ./dist/ vps:/var/www/${{ github.event.repository.name }}/dist/
          rsync -avz -e ssh ./public/dist/ vps:/var/www/${{ github.event.repository.name }}/public/dist/

          ssh vps "pm2 delete ${{ github.event.repository.name }} || true && sudo fuser -k 8080/tcp || true && pm2 start /var/www/${{ github.event.repository.name }}/dist/js/index.js --name ${{ github.event.repository.name }} --update-env"
