name: Node.js deployment

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm build

      - name: Install cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Deploy
        env:
          CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
          NAME: ${{ github.event.repository.name }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          cat <<EOF > ~/.ssh/config
          Host vps
          HostName ${{ secrets.SSH_HOST }}
          User ${{ secrets.SSH_USER }}
          IdentityFile ~/.ssh/id_ed25519
          ProxyCommand cloudflared access ssh --id ${{ secrets.CF_CLIENT_ID }} --secret ${{ secrets.CF_CLIENT_SECRET }} --hostname %h
          StrictHostKeyChecking no
          EOF

          ssh vps "mkdir -p /var/www/$NAME/dist/ /var/www/$NAME/public/dist"

          rsync -avz --delete \
            --exclude 'node_modules' \
            --exclude 'src' \
            --exclude '.git' \
            --exclude '.github' \
            --exclude '.env' \
            -e ssh ./ vps:/var/www/$NAME/

          ssh vps << SSH_EOF
            cd /var/www/$NAME
            pnpm install --prod --frozen-lockfile
            pm2 describe $NAME > /dev/null \
              && pm2 restart $NAME --update-env \
              || pm2 start dist/js/index.js --name $NAME
            pm2 save
          SSH_EOF
